# Generated by Django 6.0.7 on 2026-07-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(db_index=True, max_length=100)),
                ('chapter_number', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('verse_text', models.TextField()),
            ],
            options={
                'unique_together': {('book_name', 'chapter_number', 'verse_number')},
            },
        ),
    ]
